### ISSUE TITLE
failed at install service on RHEL 5

### ISSUE THREAD

**Issue by c4po** [thomasvandoren/puppet-redis#12]
get this error message on RHEL 5

```
err: /Stage[main]/Redis/Service[redis]/ensure: change from stopped to running failed: Could not enable redis_6379: Execution of '/sbin/chkconfig redis_6379 on' returned 1: service redis_6379 does not support chkconfig
```

need add this lines in redis.init.erb in the top, refer http://codingrecipes.com/service-x-does-not-support-chkconfig 

```
# chkconfig: 2345 95 20
# description: redis server
```

**Comment by antonbabenko** [comment]
Just fixed it. Same issue was on Amazon Linux.

**Comment by Iristyle** [comment]
Same thing on Ubuntu 12.04 ... but on 2 out of 4 machines, so a bit unpredictable ;0

**Comment by Iristyle** [comment]
So we just  tried pulling in your fix, and running on a fresh Ubuntu 12.04.

It didn't work I'm afraid, so back to the drawing board on this one.

**Comment by thomasvandoren** [comment]
@Iristyle - what error are you observing on Ubuntu 12.04?

**Comment by Iristyle** [comment]
It's bailing out at the same exact point.. everything works fine up until trying to start the service (download, extract, install, etc).  No mention of `chkconfig` however.

Again, this affected 2 of 4 machines -- using the same basebox and the same scripts, on the same version of Vagrant and VirtualBox 4.2.8.  I was a bit stumped, so I switched to a different Redis installation plugin and everything started working great.

I didn't have a lot of time to look, but there must be _something_ in the Upstart job that accounts for the differences.

https://github.com/logicalparadox/puppet-redis

**Comment by Iristyle** [comment]
His template btw

```
description "redis server <%= port %>"

start on runlevel [23]
stop on shutdown

exec sudo -u redis /opt/redis/bin/redis-server /opt/redis/redis_<%= port %>.conf

respawn
```

**Comment by Iristyle** [comment]
Apples and oranges as you're using `init` style I suppose :smile_cat: 

But maybe it's just easier to use Upstart on modern Debian / Ubuntu.

HTH

**Comment by thomasvandoren** [comment]
https://github.com/thomasvandoren/puppet-redis/pull/13 is now merged

**Comment by lucaspottersky** [comment]
Is there any plan to release a new version of puppet-redis that includes this fix?
