### ISSUE TITLE
Install one redis installation of specific version on different port

### ISSUE THREAD

**Issue by glaz666** [thomasvandoren/puppet-redis#14]
Hi!

Sorry, I am new to puppet, but I couldn't find a way to install redis on different port. If I define it as:
`class {'redis':  version=>'2.6.11' , redis_port=>1111}` - it fails with "Invalid parameter redis_port"
if I just place `redis::instance {'redis_1111' : redis_port=>'11111', version=>'2.6.11' }`\- then it fails with `version` parameter.

What is a correct way of installing redis instance of specific version and different port?

**Comment by glaz666** [comment]
Anybody? A small discussion on this happened here: https://ask.puppetlabs.com/question/754/pass-params-to-base-class/

**Comment by thomasvandoren** [comment]
In this case, I would recommend using the latest released version of the module from puppet-forge, which is currently different from master (it's less than ideal). See [Puppet Forge](http://forge.puppetlabs.com/thomasvandoren/redis) or from the [0.0.9 tag](https://github.com/thomasvandoren/puppet-redis/tree/0.0.9). Sorry for the inconvenience!

I'll have some time to go through issues and pull requests this weekend. I'll be cleaning up the docs and resolving points of confusion like this.

Thanks!
