### ISSUE TITLE
Manage logs with logrotate

### ISSUE THREAD

**Issue by thomasvandoren** [thomasvandoren/puppet-redis#2]
Add a dependency on one of the logrotate modules and setup rotation of the redis logs.

**Comment by seejohnrun** [comment]
:thumbsup:

**Comment by parhamr** [comment]
I prefer https://forge.puppetlabs.com/example42/logrotate and here’s how I use it:

``` puppet
  logrotate::rule { 'redis_6379':
    rotate       => '4',
    path         => '/var/log/redis_6379.log',
    rotate_every => 'week',
    compress     => true,
    missingok    => true
  }
```

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues and pull requests. Please fork and maintain any changes in another repo. Sorry for the inconvenience.
