### ISSUE TITLE
Push new tag for chkconfig fix?

### ISSUE THREAD

**Issue by nettles-jarrod** [thomasvandoren/puppet-redis#20]
The fix for the chkconfig error when installing is in master, but hasn't been pushed as a tag yet - can we get that tagged as a release so that Puppet Forge will install the updated module?

**Comment by nettles-jarrod** [comment]
@thomasvandoren

**Comment by nettles-jarrod** [comment]
@thomasvandoren Hey, sorry to keep bothering you on this but my team could really use a new tag here. If you're too busy I don't mind helping manage this repo - it happens. :+1:

**Comment by morgajel** [comment]
I just wanted to bump this ticket. keep up the good work.

**Comment by thomasvandoren** [comment]
https://forge.puppetlabs.com/thomasvandoren/redis/0.10.0
