### ISSUE TITLE
Update README.md to show how to use bundler when developing this module

### ISSUE THREAD

**Issue by ghost** [thomasvandoren/puppet-redis#24]
Because the project uses .gemfile instead of Gemfile (which is matches up with what PuppetLabs recommends, so that's fine), it isn't clear how to run bundler when working on the project.  It would be helpful for new developers to the module if the README gave a couple of examples of how to run bundle commands with an alternative gemfile.

I figured out how to run `bundle install --gemfile .gemfile`, but still haven't found the magic combination to run `bundle exec` with an alternative gemfile.  I'll send a pull request when I do.

**Comment by thomasvandoren** [comment]
I added the bundle install and rake instructions to the README. I believe you can set `BUNDLE_GEMFILE` when using bundle exec, but I usually just call rake directly. Please open another issue if the current README does not meet your needs.
