### ISSUE TITLE
Tag on github doesn't match tarball on puppet forge

### ISSUE THREAD

**Issue by tizzo** [thomasvandoren/puppet-redis#28]
The download from the forge still has the old syntax for variables in the templates (wihtout the `@`). This throws warnings in puppet 3.0.x, I'm not sure what needs to be done to get the downlaod tarbal to match the release on github. Perhaps push a new tag?

The current release of librarian-puppet seems to crash when trying to pull puppet-redis from git.

**Comment by thomasvandoren** [comment]
https://forge.puppetlabs.com/thomasvandoren/redis/0.10.0
