### ISSUE TITLE
Cut a fresh release to puppet forge

### ISSUE THREAD

**Issue by philandstuff** [thomasvandoren/puppet-redis#39]
The current puppet forge version is 0.0.9, which dates from December 2012.  Since then some useful stuff has gone in to master -- in particular, a lot of deprecation warnings have been fixed.  Can we have a new release please?

**Comment by thomasvandoren** [comment]
https://forge.puppetlabs.com/thomasvandoren/redis/0.10.0

**Comment by philandstuff** [comment]
Thanks! :smile:
