### ISSUE TITLE
Error: Could not find class wget

### ISSUE THREAD

**Issue by tomav** [thomasvandoren/puppet-redis#43]
I'm having this message when trying to provision my VM : `Error: Could not find class wget`.
I noticed that there are inclusion of `wget` class in the code, but there are no dependencies when the module is installed using `git submodule`.

This should be changed, or at least documented. What do you think?

**Comment by acorncom** [comment]
Ran into the same error just now.  @thomasvandoren Would be happy to help by sending in a pull request if you can outline roughly how you'd like to handle this.  Thanks!

**Comment by tiredpixel** [comment]
@tomav, @acorncom, excuse me for interposing, but this makes me curious. Perhaps one of you might be so kind as to explain a little more about how you are installing the module and resolving dependencies? I note that the `wget` dependency is contained within `metadata.json` (https://github.com/thomasvandoren/puppet-redis/blob/master/metadata.json#L12), which is as I'd personally expect given that there is no `Modulefile` (which has been deprecated). When using this module myself, I either use something which can automatically resolve module dependencies, or resolve the entire chain myself.

By way of comparison, does your method of installation also work for other modules such as `puppetlabs/ntp` (presuming you don't already have the `puppetlabs/stdlib` dependency satisfied elsewhere) (c.f. https://github.com/puppetlabs/puppetlabs-ntp/blob/master/metadata.json#L93)? I might be missing something obvious, but I can spot no `.gitmodules` there, either.

Peace, tiredpixel

**Comment by b-long** [comment]
Just ran into this myself.  Has anyone found a solution?

**Comment by overnin** [comment]
Same issue here, @acorncom could you share ur solution as a comment if you are not allowed to push PR.

**Comment by b-long** [comment]
@overnin I ended up using a solution based on http://github.com/purple52/librarian-puppet-vagrant .  The following is in my Puppetfile: 

``` yml
# Puppetfile with Redis
forge "http://forge.puppetlabs.com"

  mod "puppetlabs/stdlib"

  mod "puppetlabs/git"

  mod "puppetlabs/java"

  mod "thomasvandoren/redis"

```

**Comment by phg49389** [comment]
I just ran into this issue today. Has there been any update about this in the past 2 years?

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues and pull requests. Please fork and maintain any changes in another repo. Sorry for the inconvenience.
