### ISSUE TITLE
Add required info to init script template

### ISSUE THREAD

**Issue by kmcfate** [thomasvandoren/puppet-redis#45]
update-rc.d fails to work if default-start is empty. Please add the following to the template:

<pre>
### BEGIN INIT INFO
# Provides:             redis_<%= @redis_port %>
# Required-Start:       $syslog $remote_fs
# Required-Stop:        $syslog $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    redis-server - Persistent key-value db
# Description:          redis-server - Persistent key-value db
### END INIT INFO
</pre>

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues and pull requests. Please fork and maintain any changes in another repo. Sorry for the inconvenience.
