### ISSUE TITLE
If redis bind to more than one IP，redis can't be stoped.

### ISSUE THREAD

**Issue by UcasRichard** [thomasvandoren/puppet-redis#47]
If i set $redis_bind_address param to '127.0.0.1 192.168.1.10', i can't stop redis using command 'service redis_6379 stop'.

``` ruby
REDIS_PORT="<%= @redis_port %>"
REDIS_BIND_ADDRESS="<%= @redis_bind_address ? @redis_bind_address : '127.0.0.1' %>"

EXEC=<%= scope.lookupvar('redis::redis_bin_dir') %>/bin/redis-server
CLIEXEC="<%= scope.lookupvar('redis::redis_bin_dir') %>/bin/redis-cli -h $REDIS_BIND_ADDRESS -p $REDIS_PORT <%= @redis_password ? '-a ' + @redis_password : '' %>"
```

this code snippet is part of redis_init.erb. if redis bind to more than one IP, CLIEXEC will be a error command like '-h 127.0.0.1 192.168.1.10'. i change this comannd to '-h 127.0.0.1 -h 192.168.1.10' manual, then stop redis service successfully.

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues and pull requests. Please fork and maintain any changes in another repo. Sorry for the inconvenience.
