### ISSUE TITLE
Duplicate declaration: Package[build-essential]

### ISSUE THREAD

**Issue by nomasprime** [thomasvandoren/puppet-redis#50]
Added `include redis` to manifest and I'm getting the following error:

```
Error: Duplicate declaration: Package[build-essential] is already declared in file /tmp/vagrant-puppet/modules-9c6dae2f97a499bdc53cde514cf19c55/rbenv/manifests/deps/debian.pp:7; cannot redeclare at /tmp/vagrant-puppet/modules-9c6dae2f97a499bdc53cde514cf19c55/gcc/manifests/init.pp:17 on node vagrant-ubuntu-trusty-64.central.local
```

**Comment by Ma27** [comment]
Do you define this package somewhere in your manifests?
If so, the `ensure_packages` function might help.

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues and pull requests. Please fork and maintain any changes in another repo. Sorry for the inconvenience.
