### ISSUE TITLE
support for older redis versions?

### ISSUE THREAD

**Issue by mcandre** [thomasvandoren/puppet-redis#53]
Could we add support for older Redis versions like 2.3, 2.2, 2.1, and 2.0?

**Comment by brandongalbraith** [comment]
@mcandre See https://github.com/thomasvandoren/puppet-redis/pull/46#issue-49846742 why older Redis versions are not supported (they're no longer provided via Redis.io).

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues and pull requests. Please fork and maintain any changes in another repo. Sorry for the inconvenience.
