### ISSUE TITLE
puppet apply error： Could not find class gcc for .....

### ISSUE THREAD

**Issue by xueling795** [thomasvandoren/puppet-redis#55]
redis.pp
class { 'redis':
   version => '3.0.7'
}
Then puppet apply redis.pp ,console show it:
Warning: Could not retrieve fact fqdn
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Error: Could not find class gcc for iz257s89rxlz on node iz257s89rxlz
Error: Could not find class gcc for iz257s89rxlz on node iz257s89rxlz

env： ubuntu 14.04

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues and pull requests. Please fork and maintain any changes in another repo. Sorry for the inconvenience.
