### ISSUE TITLE
Password change keeps Puppet running

### ISSUE THREAD

**Issue by Lavaburn** [thomasvandoren/puppet-redis#56]
When changing the password of a redis server, the password is changed in the config file before restarting the server. Because of this, the init script is not able to stop Redis (wrong password...), and keeps Puppet running until the puppet run times out.

Not sure if Puppet currently enables this, but the service should be stopped before making configuration change.

**Comment by denys-mazhar-rp** [comment]
We have the same problem if you have provisioned redis instance with password, and then you just want to remove the password.
Also there is /bin/true execution in init script, so it will not fail, so you could miss this problem.

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues and pull requests. Please fork and maintain any changes in another repo. Sorry for the inconvenience.
