### ISSUE TITLE
Add setting to not install default redis instance

### ISSUE THREAD

**Issue by kirkmadera** [thomasvandoren/puppet-redis#59]
We configure multiple Redis instances on our Magento development servers and it's confusing to have one in the default that gets set up by including the `redis` class and the others in the `redis::instances` list. Preferably, we would define all instances in `redis::instances` and the `redis` class would have an option to not install a default instance.

**Comment by thomasvandoren** [comment]
Archiving this repo and closing all open issues and pull requests. Please fork and maintain any changes in another repo. Sorry for the inconvenience.
